# Generated by Django 6.0.2 on 2026-03-07 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('emoji', models.CharField(default='🏫', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Schools',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('notes', 'Unit Notes'), ('pyq', 'Previous Year Questions'), ('important', 'Important Questions'), ('tutorial', 'Tutorial / Video'), ('ebook', 'E-Book / Reference')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty_Profiles',
        ),
        migrations.AlterModelTable(
            name='material',
            table='Study_Materials',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student_Profiles',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subjects',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='api.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.school'),
        ),
    ]
