# Generated by Django 6.0.2 on 2026-03-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_alter_faculty_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='query',
            name='student',
        ),
        migrations.RemoveField(
            model_name='query',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
