# Generated by Django 6.0.2 on 2026-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_submission_assignment_remove_query_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
