# Generated by Django 6.0.2 on 2026-03-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_material_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
